version: '3'

services:
  core-api: 
    container_name: core-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    ports:
      - 8080:8080
    depends_on:
      - core-db
      - jaeger

  core-db:
    container_name: core-db
    restart: always
    image: postgres:15.0-alpine3.16
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - core-db-data:/var/lib/postgresql/data
    ports:
      - 9000:5432

  jaeger:
    container_name: jaeger
    restart: always 
    image: jaegertracing/all-in-one:latest
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    volumes:
      - jaeger-data:/badger 

volumes:
  core-db-data:
  jaeger-data:

